# -*- coding: utf-8 -*-
"""traffic_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHAkSz_OuwUUSYIiZ47NHyyMryS0OxLb
"""

# traffic_dashboard_full.py
# Full Pipeline: Train Model + Run Interactive Dashboard
# Using Plotly Dash

import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objs as go

# 1️⃣ Load data
df = pd.read_csv("Metro_Interstate_Traffic_Volume.csv")
df["date_time"] = pd.to_datetime(df["date_time"])

# 2️⃣ Feature Engineering
df["hour"] = df["date_time"].dt.hour
df["dayofweek"] = df["date_time"].dt.dayofweek
df["month"] = df["date_time"].dt.month
df["is_weekend"] = df["dayofweek"].isin([5,6]).astype(int)
df["rush_hour"] = df["hour"].isin([7,8,9,16,17,18,19]).astype(int)
df["temp_c"] = df["temp"] - 273.15
df["is_rainy"] = (df["rain_1h"] > 0).astype(int)
df["is_snowy"] = (df["snow_1h"] > 0).astype(int)
df["is_cloudy"] = (df["clouds_all"] > 50).astype(int)

df = pd.get_dummies(df, columns=["holiday","weather_main"], drop_first=True)

df = df.sort_values("date_time").reset_index(drop=True)
df["lag_1"] = df["traffic_volume"].shift(1)
df["lag_3"] = df["traffic_volume"].shift(3)
df["roll_mean_3"] = df["traffic_volume"].rolling(3).mean()
df["roll_std_3"] = df["traffic_volume"].rolling(3).std()
df = df.dropna().reset_index(drop=True)

# 3️⃣ Train/Test Split (80-20)
split_idx = int(len(df)*0.8)
train = df.iloc[:split_idx]
test = df.iloc[split_idx:]

target_col = "traffic_volume"
feature_cols = [c for c in df.columns if c not in ["date_time", target_col, "weather_description"]]

X_train, y_train = train[feature_cols], train[target_col]
X_test, y_test = test[feature_cols], test[target_col]

# 4️⃣ Train model
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

# Save model + feature columns together
joblib.dump((model, feature_cols), "traffic_model_rf.pkl")
print("✅ Model and feature columns saved: traffic_model_rf.pkl")

# 5️⃣ Initialize Dash
app = Dash(__name__)
app.title = "Traffic Volume Dashboard"

app.layout = html.Div([
    html.H1("Smart City Traffic Volume Prediction Dashboard"),

    html.Div([
        html.Label("Select Date Range:"),
        dcc.DatePickerRange(
            id='date-picker',
            min_date_allowed=df["date_time"].min().date(),
            max_date_allowed=df["date_time"].max().date(),
            start_date=df["date_time"].min().date(),
            end_date=df["date_time"].max().date()
        )
    ], style={'marginBottom': 20, 'marginTop': 20}),

    html.Div([
        html.H3("Model Performance Metrics"),
        html.Div(id='metrics-output', style={'fontSize': 18})
    ], style={'marginBottom': 20}),

    html.Div([dcc.Graph(id='traffic-graph')]),
    html.Div([dcc.Graph(id='feature-importance-graph')])
])

# 6️⃣ Callback
@app.callback(
    Output('metrics-output', 'children'),
    Output('traffic-graph', 'figure'),
    Output('feature-importance-graph', 'figure'),
    Input('date-picker', 'start_date'),
    Input('date-picker', 'end_date')
)
def update_dashboard(start_date, end_date):
    # Filter data
    mask = (df["date_time"] >= start_date) & (df["date_time"] <= end_date)
    df_filtered = df.loc[mask].copy()

    # Feature engineering (same as training)
    df_filtered["hour"] = df_filtered["date_time"].dt.hour
    df_filtered["dayofweek"] = df_filtered["date_time"].dt.dayofweek
    df_filtered["month"] = df_filtered["date_time"].dt.month
    df_filtered["is_weekend"] = df_filtered["dayofweek"].isin([5,6]).astype(int)
    df_filtered["rush_hour"] = df_filtered["hour"].isin([7,8,9,16,17,18,19]).astype(int)
    df_filtered["temp_c"] = df_filtered["temp"] - 273.15
    df_filtered["is_rainy"] = (df_filtered["rain_1h"] > 0).astype(int)
    df_filtered["is_snowy"] = (df_filtered["snow_1h"] > 0).astype(int)
    df_filtered["is_cloudy"] = (df_filtered["clouds_all"] > 50).astype(int)
    df_filtered = pd.get_dummies(df_filtered, columns=["holiday","weather_main"], drop_first=True)

    df_filtered = df_filtered.sort_values("date_time").reset_index(drop=True)
    df_filtered["lag_1"] = df_filtered["traffic_volume"].shift(1)
    df_filtered["lag_3"] = df_filtered["traffic_volume"].shift(3)
    df_filtered["roll_mean_3"] = df_filtered["traffic_volume"].rolling(3).mean()
    df_filtered["roll_std_3"] = df_filtered["traffic_volume"].rolling(3).std()
    df_filtered = df_filtered.dropna().reset_index(drop=True)

    # Align columns with training
    model, feature_cols = joblib.load("traffic_model_rf.pkl")
    for col in feature_cols:
        if col not in df_filtered.columns:
            df_filtered[col] = 0  # add missing columns with 0
    X = df_filtered[feature_cols]
    y_true = df_filtered["traffic_volume"]

    # Predict
    y_pred = model.predict(X)

    # Metrics
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    metrics_text = f"MAE: {mae:.2f} | RMSE: {rmse:.2f} | R²: {r2:.3f}"

    # Traffic graph
    traffic_fig = go.Figure()
    traffic_fig.add_trace(go.Scatter(x=df_filtered["date_time"], y=y_true, mode='lines+markers', name="Actual"))
    traffic_fig.add_trace(go.Scatter(x=df_filtered["date_time"], y=y_pred, mode='lines+markers', name="Predicted"))
    traffic_fig.update_layout(title="Actual vs Predicted Traffic Volume", xaxis_title="DateTime", yaxis_title="Traffic Volume")

    # Feature importance
    importances = pd.Series(model.feature_importances_, index=feature_cols).sort_values(ascending=False).head(15)
    feat_fig = go.Figure([go.Bar(x=importances.values, y=importances.index, orientation='h')])
    feat_fig.update_layout(title="Top 15 Feature Importances", xaxis_title="Importance", yaxis_title="Feature")

    return metrics_text, traffic_fig, feat_fig

# 7️⃣ Run app
if __name__ == '__main__':
    app.run(debug=True)

from google.colab import files
files.download('traffic_model_rf.pkl')

